# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__auto: true,
    rsync__verbose: true,
    rsync__exclude: [".git/", ".vagrant/"]
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2    
  end

  config.vm.define "manager" do |manager|
      manager.vm.box = "ubuntu/jammy64"
      manager.vm.hostname = "manager"
      manager.vm.network "private_network", ip: "192.168.56.10"
  end
  config.vm.define "node01" do |node01|
      node01.vm.box = "ubuntu/jammy64"
      node01.vm.hostname = "node01"
      node01.vm.network "private_network", ip: "192.168.56.20"
      node01.vm.network "forwarded_port", guest: 8081, host: 8081
      node01.vm.network "forwarded_port", guest: 8087, host: 8087
      node01.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 2
    end
  end
  config.vm.define "node02" do |node02|
      node02.vm.box = "ubuntu/jammy64"
      node02.vm.hostname = "node02"
      node02.vm.network "private_network", ip: "192.168.56.30"
      node02.vm.network "forwarded_port", guest: 80, host: 8080
      node02.vm.network "forwarded_port", guest: 5432, host: 5432
  end
end